### ISSUE TITLE
#投稿《站在巨人的肩膀上》，MD格式

### ISSUE THREAD

**Issue by 459064124** [xunlutzp/xunlutzp.github.io#21]
# 站在巨人的肩膀上
“我们便如同巨人肩膀上的侏儒，可以看得更远，并不是因为我们视觉敏锐或天赋异禀，而是因为他们巨大的身躯把我们抬起来，让我们居高临下。”为何在此引用这句话呢? 目的之一是阐述个人关于方法论的看法，目的之二是表明个人对时事热点的立场。

## 社会化学习
“社会化学习”化用了编程的概念：开源（*Open Source*）与社会化编程（*Social Coding*）。“让全世界码农看自己的代码”，与全世界的开源开发者交流代码或心得，这对于部分计算机专业的工作人员是具有吸引力的。在狭小的空间里呆上很长时间后，就会有豁然开朗的感觉；在名利竞争场中脱身而出，也会有复得返自然的欣喜。   
在互联网时代，杂乱的信息充斥，单纯利用百度无法实现“精准”检索，我们迫切需要找到无限接近“真实”的答案。如何寻找“精准”且“真实”的答案呢？在我看来，“社会化学习”这种交互式的学习方法可以提供不一样的思路。

***Github网址***: *Github*中有许多值得借鉴的《申请指南》和《生存手册》等，值得挖掘、利用、借鉴与补充。

**图书馆官网与服务群**：学校订阅了很多电子数据库，包括而不局限于文献阅览（*Embase*, *Cochrane library*等），软件下载（*Endnote*, *Noteexpress*等），视频获取（*JOVE*实验视频数据库）等。

***UpToDate*软件与网址**：建议使用*UpToDate*、谷歌、维基百科、知乎、丁香园、*the Student Doctor Network*。*UpToDate*是以循证医学为基础的优质临床决策支持工具，以即时、权威的内容，帮助医疗机构优化临床决策，提升医疗质量。*UpToDate*为临床医生提供现有的高质量临床实用信息，操作简单，帮助其在诊疗过程中快速制定优质决策。

**循证医学**：循证医学，英文解释为*Evidence-based medicine*，它意味着重大的临床决策是有理可依，有理可循。推荐大家阅览*Gordon Guyatt*主编，刘晓清主译的《循证临床实践手册》。关于肿瘤治疗方案是否“符合规范”的问题，凭借现有临床证据和专家指南是能够评价的。如前所述，推荐大家利用*UpToDate*，或者检索*Pubmed/Embase*，或者*Google*各国临床指南。

**师长&学长学姐&同学的帮助**：古语中有“醍醐灌顶”，“仙人抚我顶，结发受长生”，“真传一句话，假传万卷书”等名句，这表明了“外援”或“擅加于物”的重要性。正如《礼记》：独学而无友，必孤陋寡闻也。

在循证医学中，“同质性”是证据应用于临床的重要前提。正如井里的青蛙，不可与它们谈论大海；夏天的昆虫，不可与它们谈论冰雪；对见识浅陋却沾沾自喜的人，不可与他们谈论大道。基于此原因，许多陈词滥调/颓废沮丧的言论对我们而言是井底的蛙声，或是夏日的虫鸣，对这些外物的过分关注将导致神圣而明、造化天成的禀赋丧失，这将是有害无益的。这时有意识地屏蔽外界的“杂音”，专心致力于自身能力的发展是重要的！

社会化学习同样意味着观念上的转变。在“检索事实”和“执行力”达到精通后，个人核心能力的发展将自然而然地提升。但个人的发展离不开社会的支持系统。如果将医院比喻为修真小说中的门派，那么本科阶段是外门弟子，硕博阶段是内门弟子，主治医师是真传弟子，副主任医师为长老，主任医师是太上长老，我们今后会停留在那个阶段？悲观地说，我们无法每个人都留在最顶级的门派中，担任最重要的角色，我们的发展会受到阻碍。

我们唯独希望，当受到环境与才能的限制之后，核心能力发展受到阻碍，我们只能停留在半山腰上，见不到山顶上的风景时，我们能够乐天知命。我们希望我们的脚下，在半山腰之下，所有阻碍都不复存在，所有荆棘全部都化作了坦途。尽管才华不够横溢，天赋不够突出，外物的力也不够直上青云，但我们朝着最峰巅的医学殿堂前进的心情是一样的，让病人少流一滴泪水的心思也是一样的。

就我们目前的《寻路桐梓坡》而言，它是初级阶段的，它依旧是待补充，待修订，待完善的。它是我们医学道路上第一道关卡的缩影，是一群充满善意的朋友们给大家的礼物。2021年初稿完成之际，并非功成之日！《寻路桐梓坡》这本手册没有“功成”，主要撰写这本手册的16级的同学们也没有到“功成”的境界。

那么什么时候，我们这本手册会到真正的功成之日呢？只要医学知识还在更新，只要病人受到疾患的折磨，只要桐梓坡还有寻道求索的医学学子，那么就没有真正“功成之日”。

那么什么时候，我们16级的同学会到真正的功成之日呢？那将是很多年之后的故事了，也许是四五十年后？我们大多数同学即将进入了研究生阶段，三五年后，我们或许会以类似的形式，整理我们另一个“三年”或“五年”的故事。它或许是专硕规培期间的点滴，或许是高分SCI论著的发表经历，或许是国际顶尖学术会议的公开发言，或许是海外联合培养或攻读PhD的历程，这或许将会是我们第二道关卡的故事......这有待未来一届执行编辑的联系和同学们的认同和参与。

## 《手册》与《指南》推荐

1. 生物信息学：*Bioinformatics Tutorial – Basic*，清华大学鲁志实验室   
链接：https://lulab2.gitbook.io/teaching/

2. 实验室指南：*Lab Guide*实验室指南，清华大学鲁志实验室   
链接：https://lulab.gitbook.io/docs/

3. 上海交通大学飞跃手册  
链接：https://survivesjtu.github.io/SJTU-Application/#/

4. 南方科技大学飞跃手册-2019-*Fall*   
链接：https://sustech-application.github.io/2019-Fall/#/

5. *KAUST*生存手册   
链接：https://kaustian-handbook-cn.readthedocs.io/en/latest/

6. 脑科学博士申请指南   
链接：https://brainphd-cn.github.io/handbook/short-intro/

7. 计算生物/生物信息*PhD*申请指北   
链接：https://compbio-phd-cn.github.io/handbook/other_resource/

8. *awesome-single-cell*   
链接：https://github.com/seandavi/awesome-single-cell

9. 生物信息培训免费资料   
链接：http://www.ehbio.com/Training/index.php/Home/Index/Articles.html

10. 待更新……

**Comment by zcx980605** [comment]
已经收录，Commit ID: [cc459bf](https://github.com/xunlutzp/xunlutzp.github.io/commit/cc459bf3e6a6dbfff407a4092a8d6b5472f6787f)
